### ISSUE TITLE
[Projet] Broken Subscribe link

### ISSUE THREAD

**Issue by rdekimpe1400** [UCLOUVAIN-CLUB-ELEC/UCLOUVAIN-CLUB-ELEC.github.io#3]
The "Subscribe" link at the bottom of the project page does not work. It points to https://uclouvain-club-elec.github.io/feed.xml which does not exist.
Maybe the subscribe link is not necessary at all.

**Comment by jeertmans** [comment]
Indeed, in don't think RSS flux links are necessary at all :-) I will remove it, we can add this in the future if this seems useful.
