### ISSUE TITLE
"404 Page not found :(" on event 10.03.2022

### ISSUE THREAD

**Issue by rdekimpe1400** [UCLOUVAIN-CLUB-ELEC/UCLOUVAIN-CLUB-ELEC.github.io#9]
J'ai ajouté les événements InfluencAir dans l'agenda. Ils apparaissent bien dans le calendrier, mais quand on clique dessus il renvoie une erreur "page not found". Je n'ai pas trouvé d'où ça venait...

**Comment by jeertmans** [comment]
Je regarde  à ça ;-)
